name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run linkspector
      uses: umbrelladocs/action-linkspector@37c85bcde51b30bf929936502bac6bfb7e8f0a4d # v1.4.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        config_file: .github/linters/linkspector.yml
        fail_on_error: true
        filter_mode: nofilter
